//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELearningContainer : DbContext
    {
        public ELearningContainer()
            : base("name=ELearningContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Courseware> Courseware { get; set; }
        public virtual DbSet<Paper> Paper { get; set; }
        public virtual DbSet<Quiz> Quiz { get; set; }
        public virtual DbSet<Claim> Claim { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Action_UserCourse> Action_UserCourse { get; set; }
        public virtual DbSet<Action_UserQuiz> Action_UserQuiz { get; set; }
    }
}
